### ISSUE TITLE
The dashboard doesn't display doughnuts on DCOS

### ISSUE THREAD

**Issue by s-urbaniak** [mesosphere/kubernetes-mesos#703] opened 2015-12-15 17:39 UTC
When install kubernetes, showing the service no doughnuts are being displayed.

**Comment by s-urbaniak** [comment] 2015-12-15 17:39
![screen shot 2015-12-15 at 18 38 21](https://cloud.githubusercontent.com/assets/375856/11818546/3723fc9a-a35b-11e5-9b75-95b8cadce99b.png)

**Comment by s-urbaniak** [comment] 2015-12-15 17:56
The UI makes two calls which fail:
1. machine
```
Request:
GET http://pool-7fc7-elasticl-rzwzru03zo4m-1052136347.us-west-2.elb.amazonaws.com/service/kubernetes/api/v1/proxy/nodes/10.0.4.149:4194/api/v1.0/machine

Response:
< HTTP/1.1 503 Service Unavailable
< Content-Type: text/plain; charset=utf-8
< Date: Tue, 15 Dec 2015 17:55:34 GMT
< Server: openresty/1.7.10.2
< Content-Length: 112
< Connection: keep-alive
Error: 'dial tcp 10.0.4.149:4194: connection refused'
Trying to reach: 'http://10.0.4.149:4194/api/v1.0/machine'
```

2. containers
```
Request:
GET http://pool-7fc7-elasticl-rzwzru03zo4m-1052136347.us-west-2.elb.amazonaws.com/service/kubernetes/api/v1/proxy/nodes/10.0.4.149:4194/api/v1.0/containers/

Response:
Error: 'dial tcp 10.0.4.149:4194: connection refused'
Trying to reach: 'http://10.0.4.149:4194/api/v1.0/containers/'
```

**Comment by karlkfi** [comment] 2015-12-16 00:09
I think this is the code generating that url: https://github.com/kubernetes/kube-ui/blob/master/master/shared/js/modules/services/cAdvisor.js#L6-L11

I assume `ENV['/']['cAdvisorProxy']` is nil so `k8sApi.getUrlBase()` = `http://pool-7fc7-elasticl-rzwzru03zo4m-1052136347.us-west-2.elb.amazonaws.com/service/kubernetes/api/v1`.

I've never heard of a node proxy tho... I assume it's a real thing, but I have no idea how it works.

**Comment by s-urbaniak** [comment] 2015-12-16 14:52
OK, this is really strange, I just rechecked on a CCM to be shown in the all hands and now the doughnuts work. Maybe Google updated the kube-ui image:

![screen shot 2015-12-16 at 15 51 01](https://cloud.githubusercontent.com/assets/375856/11844055/faa823a6-a40c-11e5-8df2-a28eca2e9178.png)

@karlkfi Do you mind rechecking on a vanilla CCM?

**Comment by karlkfi** [comment] 2015-12-16 22:12
Sure, i'll check again.

**Comment by karlkfi** [comment] 2015-12-16 23:05
Still seeing the same problem:

![screen shot 2015-12-16 at 3 05 04 pm](https://cloud.githubusercontent.com/assets/3980984/11856546/7bc67606-a406-11e5-8b29-9d40d327dd85.png)

**Comment by karlkfi** [comment] 2015-12-16 23:15
Bonus: The guestbook example deploys and says it's running, but doesn't work. The form submit fails in javascript:

```
<br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis-slave:6379]' in /usr/local/lib/php/Predis/Connection/AbstractConnection.php:168
Stack trace:
#0 /usr/local/lib/php/Predis/Connection/StreamConnection.php(97): Predis\Connection\AbstractConnection-&gt;onConnectionError('php_network_get...', 0)
#1 /usr/local/lib/php/Predis/Connection/StreamConnection.php(58): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\Parameters))
#2 /usr/local/lib/php/Predis/Connection/AbstractConnection.php(94): Predis\Connection\StreamConnection-&gt;createResource()
#3 /usr/local/lib/php/Predis/Connection/StreamConnection.php(158): Predis\Connection\AbstractConnection-&gt;connect()
#4 /usr/local/lib/php/Predis/Connection/AbstractConnection.php(193): Predis\Connection\StreamConnection-&gt;connect()
#5 /usr/local/lib/php/Predis/Connection/StreamConnection.php(184): Predis\Connection\AbstractConnection-&gt;getResour in <b>/usr/local/lib/php/Predis/Connection/AbstractConnection.php</b> on line <b>168</b><br />
```

**Comment by karlkfi** [comment] 2015-12-17 00:08
kube-ui seems to be erroring because for a 500 response from `http://karl-04te-elasticl-jgz33qa088zb-1592330004.us-west-2.elb.amazonaws.com/service/kubernetes/api/v1/proxy/nodes/10.0.5.229:4194/api/v1.0/containers/` and similar urls, which look like some sort of node proxy.

The node IP in all the URLs is the public slave node (tho i'm not sure if that's significant).

**Comment by karlkfi** [comment] 2015-12-17 00:18
Hitting the URL directly seems to indicate that none of the nodes are registered with the node proxy:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "host IP unknown; known addresses: []",
  "code": 500
}
```

https://github.com/kubernetes/kubernetes/blob/master/pkg/util/node/node.go#L60

**Comment by karlkfi** [comment] 2015-12-17 00:29
from apiserver.log - the last two messages repeat as long as kube-ui is up.

```
I1216 23:07:41.340874     463 mesos.go:75] new mesos cloud, master='zk://master.mesos:2181/mesos'
I1216 23:07:41.341095     463 master.go:368] Node port range unspecified. Defaulting to 30000-32767.
I1216 23:07:41.347736     463 client.go:155] cloud master changed to '10.0.4.134:5050'
[restful] 2015/12/16 23:07:41 log.go:30: [restful/swagger] listing is available at https://10.0.1.150:25502/swaggerapi/
[restful] 2015/12/16 23:07:41 log.go:30: [restful/swagger] https://10.0.1.150:25502/swaggerui/ is mapped to folder /swagger-ui/
W1216 23:07:41.379183     463 controller.go:212] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[]} [{[{10.0.1.150 <nil>}] [] [{ 25502 TCP}]}]}
I1216 23:07:41.381202     463 server.go:609] Serving securely on 10.0.1.150:25502
E1216 23:07:42.253976     463 server.go:619] Unable to generate self signed cert: open /var/run/kubernetes/apiserver.crt: permission denied
I1216 23:07:42.254024     463 server.go:651] Serving insecurely on 10.0.1.150:25503
E1216 23:07:42.254092     463 server.go:633] Unable to listen for secure (open /var/run/kubernetes/apiserver.crt: no such file or directory); will try again.
E1216 23:07:57.254352     463 server.go:633] Unable to listen for secure (open /var/run/kubernetes/apiserver.crt: no such file or directory); will try again.
E1216 23:08:12.254606     463 server.go:633] Unable to listen for secure (open /var/run/kubernetes/apiserver.crt: no such file or directory); will try again.
E1216 23:08:14.234193     463 errors.go:62] apiserver received an error that is not an unversioned.Status: host IP unknown; known addresses: []
E1216 23:08:14.259632     463 errors.go:62] apiserver received an error that is not an unversioned.Status: host IP unknown; known addresses: []
```

**Comment by karlkfi** [comment] 2015-12-17 00:41
The public slave node says it's pending. Not sure if that matters. There are no tasks running on it. So I wouldn't expect a kubelet to even exist there yet, much less have registered, but I don't know how the node registration works with k8sm.

```
$ dcos kubectl get node 10.0.5.229 -o=yaml
apiVersion: v1
kind: Node
metadata:
  creationTimestamp: 2015-12-16T23:07:44Z
  labels:
    k8s.mesosphere.io/attribute-public_ip: "true"
    kubernetes.io/hostname: 10.0.5.229
  name: 10.0.5.229
  resourceVersion: "3564"
  selfLink: /api/v1/nodes/10.0.5.229
  uid: d0f1492e-a449-11e5-bd31-0a21d7779d67
spec:
  externalID: 10.0.5.229
status:
  conditions:
  - lastHeartbeatTime: 2015-12-17T00:38:56Z
    lastTransitionTime: null
    message: mesos reports ready status
    reason: SlaveReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 0
  nodeInfo:
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: ""
    kubeletVersion: ""
    machineID: ""
    osImage: ""
    systemUUID: ""
  phase: Pending
```

**Comment by karlkfi** [comment] 2015-12-17 01:00
The kube-ui dashboard starts working as soon as you try to schedule something on the public slave.

I added the following annotation to the guestbook to try this:

```
      annotations:
        k8s.mesosphere.io/roles: slave_public
```

Even before the guestbook frontends are `Running`, the kubelet starts on that node and kube-ui starts functioning again.

FWIW, the node still describes itself as `Pending`. So I assume that's not related.  But there is now `nodeInfo` populated:

```
$ dcos kubectl get node 10.0.5.229 -o=yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    k8s.mesosphere.io/executorId: 6f8fdd082fc306fc_k8sm-executor
    k8s.mesosphere.io/executorResources: CgRjcHVzEAAaCQkAAAAAAADQPzIMc2xhdmVfcHVibGlj,CgNtZW0QABoJCQAAAAAAAGBAMgxzbGF2ZV9wdWJsaWM=
  creationTimestamp: 2015-12-16T23:07:44Z
  labels:
    k8s.mesosphere.io/attribute-public_ip: "true"
    kubernetes.io/hostname: 10.0.5.229
  name: 10.0.5.229
  resourceVersion: "4631"
  selfLink: /api/v1/nodes/10.0.5.229
  uid: d0f1492e-a449-11e5-bd31-0a21d7779d67
spec:
  externalID: 10.0.5.229
status:
  addresses:
  - address: 10.0.5.229
    type: LegacyHostIP
  - address: 10.0.5.229
    type: InternalIP
  capacity:
    cpu: "4"
    memory: 13891Mi
    pods: "40"
  conditions:
  - lastHeartbeatTime: 2015-12-17T00:57:46Z
    lastTransitionTime: null
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  - lastHeartbeatTime: 2015-12-17T00:57:46Z
    lastTransitionTime: 2015-12-17T00:56:15Z
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  nodeInfo:
    bootID: d6d313ab-dd77-4b13-acb2-b8d5520e1d6b
    containerRuntimeVersion: docker://1.8.3
    kernelVersion: 4.2.2-coreos-r1
    kubeProxyVersion: v0.7.1-v1.1.3
    kubeletVersion: v0.7.1-v1.1.3
    machineID: bd0834823c0c41b09fc506a2644b1a6f
    osImage: CoreOS 835.8.0
    systemUUID: EC201BD5-2744-2AE7-16CA-CBA2980C2BDF
  phase: Pending
```

**Comment by karlkfi** [comment] 2015-12-17 01:06
Looks like the NodeStatus.Addesses isn't being populated until the kubelet is actually started, which causes 500 errors when trying to query the node through the apiserver proxy.

This makes sense, because the node doesn't actually exist yet. K8sm just fakes it into existence, which it didn't used to do. Previously the node list only included nodes that had started already.

The mesos/docker cluster never suffers this problem, because it only has two nodes and they're always up, due to kube-dns and kube-ui being deployed.

I'm going to see if I can replicate with 3 nodes on mesos/docker on master.

**Comment by karlkfi** [comment] 2015-12-17 01:28
Confirmed. This has nothing to do with roles support, specifically. It is simply that we now pre-register nodes that are unavailable, and kube-ui sees them and tries to get their resource and container usage, which returns a 500, which causes the UI to explode.

The same behavior can be seen on master:

```
NUM_NODES=5 ./cluster/kube-up.sh
```

**Comment by karlkfi** [comment] 2015-12-17 01:31
I personally think this is a regression and blocker that should inhibit a new release, but we can discuss it.

I suspect the correct solution is to make kube-ui tolerate not-running nodes. Then we just need to update the node running/readiness status when a real kubelet registers (which I think I remember seeing a PR for recently).

**Comment by karlkfi** [comment] 2015-12-17 01:39
It might be possible to hack in a workaround that adds `NodeStatus.Addesses` whenever the node is originally registered, but I don't know what side effects that would cause or whether it would actually fix the display or just delay the problem to another error.

**Comment by karlkfi** [comment] 2015-12-17 01:47
Looking at the nodes on master, they all show up as "Ready" even if they don't actually exist. Kube-UI already looks for readiness. So Kube-UI is already doing the "right" thing, k8sm is just lying to it.

**Comment by karlkfi** [comment] 2015-12-17 01:56
This PR recently added `Ready=True` as a default k8sm node condition: https://github.com/kubernetes/kubernetes/pull/18349

**Comment by karlkfi** [comment] 2015-12-17 02:37
I tried flipping the initial `Ready=True` to Ready=False`, but that seems to cause scheduling to fail. kube-dns never comes up. I haven't figured out exactly why.

**Comment by karlkfi** [comment] 2015-12-17 02:42
Reverting https://github.com/kubernetes/kubernetes/pull/18349 locally on master (kube-ui:v4) also doesn't fix the problem.

**Comment by karlkfi** [comment] 2015-12-17 03:16
Flipping the `Ready=True` to `Ready=False` in the StatusUpdater (https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/node/statusupdater.go#L133) allows the cluster to at least come up. All nodes start `Ready=True` and then the StatusUpdater sets all the nonexistent ones to `Ready=False` about 20s later.

```
$ ./cluster/kubectl.sh get nodes
NAME          LABELS                                                                                                       STATUS     AGE
172.17.0.10   k8s.mesosphere.io/attribute-gen=2013,k8s.mesosphere.io/attribute-rack=3,kubernetes.io/hostname=172.17.0.10   NotReady   1m
172.17.0.6    k8s.mesosphere.io/attribute-gen=2011,k8s.mesosphere.io/attribute-rack=1,kubernetes.io/hostname=172.17.0.6    Ready      1m
172.17.0.9    k8s.mesosphere.io/attribute-gen=2012,k8s.mesosphere.io/attribute-rack=2,kubernetes.io/hostname=172.17.0.9    Ready      1m
```

Unfortunately, kube-ui still doesn't work with this state. It gives another error:

```
ReferenceError: hostname is not defined
    at app.js:1
    at Qn (base.js:21)
    at Function.ke (base.js:21)
    at o.all.then.e.loading (app.js:1)
    at u (base.js:6)
    at base.js:6
    at $.$eval (base.js:7)
    at $.$digest (base.js:7)
    at $.$apply (base.js:7)
    at o (base.js:6)
```

(It's really hard to debug compressed javascript.)

Speculation: Do the kubelets not heartbeat `Ready=True`? Or does the fact that they're not immediately ready cause the deployment to fail before they heartbeat that they're ready? Either would explain why kube-dns doesn't come up when the nodes are created with `Ready=False`.

**Comment by karlkfi** [comment] 2015-12-17 03:37
Adding NodeStatus.Addesses up front (at node creation) just causes yet another error in kube-ui.

```
			Addresses: []api.NodeAddress{
				{
					Type: api.NodeLegacyHostIP,
					Address: hostName,
				},
				{
					Type: api.NodeInternalIP,
					Address: hostName,
				},
			},
```

```
TypeError: Cannot read property 'cpu' of undefined
    at app.js:1
    at Qn (base.js:21)
    at Function.ke (base.js:21)
    at o.all.then.e.loading (app.js:1)
    at u (base.js:6)
    at base.js:6
    at $.$eval (base.js:7)
    at $.$digest (base.js:7)
    at $.$apply (base.js:7)
    at o (base.js:6)
```

This appears to be complaining about not knowing the NodeStatus.Capacity.CPU, which is impossible to accurately centrally pre-register, because the executors have not yet auto-detected node-specific resources. We could pre-set default capacity to zero, but it would be a bit of a hack. It seems kube-ui assumes created nodes have populated statuses, which seems dubious. It seems perfectly reasonable for a node to register itself before being fully status populated...

**Comment by karlkfi** [comment] 2015-12-17 03:53
Adding both Addresses & Capacity AND changing StatusUpdater to mark nonexistant nodes as NotReady "fixes" kube-ui:

```
			Addresses: []api.NodeAddress{
				{
					Type: api.NodeLegacyHostIP,
					Address: hostName,
				},
				{
					Type: api.NodeInternalIP,
					Address: hostName,
				},
			},
			Capacity: api.ResourceList{
				api.ResourceName(api.ResourceCPU): resource.MustParse("0"),
				api.ResourceName(api.ResourceMemory): resource.MustParse("0"),
				api.ResourceName(api.ResourceStorage): resource.MustParse("0"),
			},
```

```
$ ./cluster/kubectl.sh get nodes
NAME          LABELS                                                                                                       STATUS     AGE
172.17.0.10   k8s.mesosphere.io/attribute-gen=2012,k8s.mesosphere.io/attribute-rack=2,kubernetes.io/hostname=172.17.0.10   NotReady   3m
172.17.0.6    k8s.mesosphere.io/attribute-gen=2011,k8s.mesosphere.io/attribute-rack=1,kubernetes.io/hostname=172.17.0.6    Ready      3m
172.17.0.9    k8s.mesosphere.io/attribute-gen=2013,k8s.mesosphere.io/attribute-rack=3,kubernetes.io/hostname=172.17.0.9    Ready      3m
```

Unfortunately, it still shows the nonexistent node, even tho it's marked as NotReady.

![screen shot 2015-12-16 at 7 51 05 pm](https://cloud.githubusercontent.com/assets/3980984/11860865/5e62ae54-a42e-11e5-98a8-24ebbb937001.png)

**Comment by karlkfi** [comment] 2015-12-17 03:54
So, yeah. That's a big hack, and I don't really want to do it. But the alternative is to require a new version of kube-ui that deals with NotReady nodes correctly.

**Comment by karlkfi** [comment] 2015-12-17 03:55
@sttts @s-urbaniak You know this code better. Got any better ideas?

Ideally (imo) the nonexistent nodes would always be marked as NotReady (provided that doesn't inhibit scheduling to them). But I don't know how to get that to work...

**Comment by sttts** [comment] 2015-12-17 05:56
@karlkfi thanks for the great analysis. My two cents:

- the Pending flags is still in the API, but abandoned. It has no effect on the node logic.
- We actually know the capacity from state.json I believe. We could set correct values in the node upfront.
- I don't think it helps to set addresses upfront. If the kubelet does not run yet, we get the same 500 error, don't we?
- We have to synchronize our NodeReady logic with that of the node controller. If a node is not ready for some time, the node controller will evict pods, compare: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L418. I was of the impression that it also deletes those nodes. But as far as I see now, the (current) logic is to ask the cloud provider about the nodes' existence. So maybe setting the NodeReady condition to false is actually an option.
- I don't think reverting kubernetes/kubernetes#18349 help because it only set a NodeReady condition before the StatusUpdate controller does the same.
- As the scheduler is under our control, having nodes unready is not a huge deal. I would have expected that scheduling even works now onto unready nodes.
- The main reason to set all nodes to ready was cosmetical. It looks odd IMO that a node which is up is not ready.
- The described behavior has been introduced in v0.7.0 or even before. I don't see this as a blocker for v0.

**Comment by sttts** [comment] 2015-12-17 07:25
Setting the NodeReady condition to false doesn't work either. How can we make sure that the node controller not evict the node between pods being created and the kubelet is started?

**Comment by sttts** [comment] 2015-12-17 21:58
Have done tests today with v0.7.0. As soon as one node has no kubelet we see the same behavior. The difference with v0.7.1 is that kube-ui even fails for any freshly installed cluster because we always have the public slave without the kubelet by default.

I will investigate whether we can easily fix this in kube-ui itself. I think tweaking the Ready condition is not the right solution for the issue.

**Comment by s-urbaniak** [comment] 2015-12-18 15:44
Thanks to @sttts we have a quick fix for 0.7.1!
https://github.com/sttts/kube-ui/commits/sttts-unready-fixes

The above kube-ui version is currently used in `release-v0.7-v1.1` 
https://github.com/mesosphere/kubernetes/commit/24f890ebec1f1b2d12d9c215ee14eb07b895dc3f

I verified on a vanilla DCOS install that the doughnuts are being displayed again:
![screen shot 2015-12-18 at 16 38 06](https://cloud.githubusercontent.com/assets/375856/11900502/a83fea0e-a5a6-11e5-9b0d-fdcd72aca56b.png)

**Comment by s-urbaniak** [comment] 2015-12-18 15:46
@karlkfi PTAL

**Comment by karlkfi** [comment] 2015-12-18 23:54
Looks good! I'm still not sure I like having nodes show up empty with no resources, but it's better than the alternative, and good enough for a quick fix. We'll have to be more thorough for the upstream fix.

Here's a larger cluster (with 3x oinker instances load balanced on public slaves!):

![screen shot 2015-12-18 at 3 52 20 pm](https://cloud.githubusercontent.com/assets/3980984/11909714/8dda6ef2-a59f-11e5-8b07-34d50a47c7e5.png)

**Comment by karlkfi** [comment] 2015-12-18 23:54
Closing, since follow up is in #712

**Closed by karlkfi** 2015-12-18 23:54 UTC
Labels: class/bug, PTAL

**Comment by sttts** [comment] 2015-12-19 09:07
@karlkfi I agree. It's debatable whether we want to show unready nodes. The whole kube-ui is deprecated though, replaced soon by the dashboard. I think it's fine for the moment.
