### ISSUE TITLE
Nginx Example - Wrong dockerfile

### ISSUE THREAD

**Issue by tomuench** [mesosphere/kubernetes-mesos#235] opened 2015-04-29 13:11 UTC
Hello,

maybe i have found an issue on the nginx example. In the example files **controller-nginx.json** and **pod-nginx.json** there is the docker-image **dockerfile/nginx** defined. This doesn't exist in the dockerhub. If i switch the image to **nginx**, there will be no error anymore.

In the logs i had seen this error:

I0429 14:04:42.195761    8186 event.go:138] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginxcontroller-53047", UID:"40a5433c-ee67-11e4-8cc0-000c29611ae4", APIVersion:"v1beta1", ResourceVersion:"2389", FieldPath:"spec.containers{nginx}"}): reason: 'failed'  **Failed to pull image"dockerfile/nginx"**: Error: image dockerfile/nginx:latest not found

Best Wishes,

Tobias

**Comment by jdef** [comment] 2015-05-04 14:45
duplicate of #241

**Closed by jdef** 2015-05-04 14:45 UTC
Labels: duplicate
