### ISSUE TITLE
can't lanuch k8sm  executor

### ISSUE THREAD

**Issue by yangzhares** [mesosphere/kubernetes-mesos#226] opened 2015-04-17 05:19 UTC
lanuch k8sm executor happened the following error:
Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: I0417 05:13:35.191386    1482 executor.go:112] Init mesos executor driver
Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: I0417 05:13:35.191393    1482 executor.go:113] Version: 0.20.0
Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: E0417 05:13:35.191405    1482 executor.go:117] Failed to parse environments: **Cannot find MESOS_SLAVE_PID** in the environment
Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: E0417 05:13:35.191415    1482 executor.go:104] failed to initialize the driver: **Cannot find MESOS_SLAVE_PID** in the environment
Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: F0417 05:13:35.191423    1482 service.go:308] failed to create executor driver: **Cannot find MESOS_SLAVE_PID** in the environment

unit file as:
[Unit]
Description=Kubernetes Kubelet Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service cadvisor.service
Requires=docker.service

[Service]
WorkingDirectory=/var/lib/kubelet
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/kubelet
ExecStart=/usr/local/bin/km executor \
     --address=${KUBE_HOST} \
     --hostname_override=${KUBE_HOST} \
     --api_servers=${KUBE_MASTER} \
     --port=10250 \
     --v=${KUBE_LOG_LEVEL}

Restart=on-failure

[Install]
WantedBy=multi-user.target

please help check how to fix this issue, thanks in advance.

**Comment by jdef** [comment] 2015-04-17 14:08
It looks like you're attempting to launch the kubelet-executor directly via
systemd, instead of via mesos. This is intended to fail by design. It is
expected that Mesos slaves will launch all Mesos executor processes, they
are not managed independently by systemd.

What's the overall problem that you're trying to tackle?


On Fri, Apr 17, 2015 at 1:19 AM, Clare <notifications@github.com> wrote:

> lanuch k8sm executor happened the following error:
> Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: I0417 05:13:35.191386 1482
> executor.go:112] Init mesos executor driver
> Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: I0417 05:13:35.191393 1482
> executor.go:113] Version: 0.20.0
> Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: E0417 05:13:35.191405 1482
> executor.go:117] Failed to parse environments: *Cannot find
> MESOS_SLAVE_PID* in the environment
> Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: E0417 05:13:35.191415 1482
> executor.go:104] failed to initialize the driver: *Cannot find
> MESOS_SLAVE_PID* in the environment
> Apr 17 05:13:35 ct7-k8s-minion-1 km[1482]: F0417 05:13:35.191423 1482
> service.go:308] failed to create executor driver: *Cannot find
> MESOS_SLAVE_PID* in the environment
>
> unit file as:
> [Unit]
> Description=Kubernetes Kubelet Server
> Documentation=https://github.com/GoogleCloudPlatform/kubernetes
> After=docker.service cadvisor.service
> Requires=docker.service
>
> [Service]
> WorkingDirectory=/var/lib/kubelet
> EnvironmentFile=-/etc/kubernetes/config
> EnvironmentFile=-/etc/kubernetes/kubelet
> ExecStart=/usr/local/bin/km executor \
> --address=${KUBE_HOST} \
> --hostname_override=${KUBE_HOST} \
> --api_servers=${KUBE_MASTER} \
> --port=10250 \
> --v=${KUBE_LOG_LEVEL}
>
> Restart=on-failure
>
> [Install]
> WantedBy=multi-user.target
>
> please check how to fix this issue, thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/226>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by yangzhares** [comment] 2015-04-19 15:31
Thanks, i want to install mesos-kubernetes  in my local environment. i'm not very familiar with mesos, if launch kubelet-executor via mesos, how to do it? can you give a README?

**Comment by jdef** [comment] 2015-04-20 11:55
see
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/mesos.md

On Sun, Apr 19, 2015 at 11:31 AM, Clare <notifications@github.com> wrote:

> Thanks, i want to install mesos-kubernetes in my local environment. i'm
> not very familiar with mesos, if launch kubelet-executor via mesos, how to
> do it? can you give a README?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/226#issuecomment-94288576>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by jdef** [comment] 2015-04-28 18:49
closing this out for now.

**Closed by jdef** 2015-04-28 18:49 UTC
Labels: wontfix
