### ISSUE TITLE
no buildable Go source files in /pkg/src/github.com/google/cadvisor/info

### ISSUE THREAD

**Issue by jsm** [mesosphere/kubernetes-mesos#164] opened 2015-03-05 23:23 UTC
Running into a problem trying to follow this guide: http://mesosphere.com/docs/tutorials/kubernetes-mesos-gcp/

I get to the step where I'm directed to build the mesosphere version of kubernetes, and this happens:

```shell
$ sudo docker run --rm -v $(pwd)/bin:/target mesosphere/kubernetes-mesos:build
Unable to find image 'mesosphere/kubernetes-mesos:build' locally
Pulling repository mesosphere/kubernetes-mesos
462d7cdf3da0: Download complete
511136ea3c5a: Download complete
30d39e59ffe2: Download complete
c90d655b99b2: Download complete
29f51bae2f85: Download complete
6242daf50c65: Download complete
344a44a022be: Download complete
23fb97a7cc40: Download complete
1fbf1e30ca47: Download complete
8f41e6ac22e3: Download complete
d9a633a35376: Download complete
4df13c97bd19: Download complete
9c491ae4238b: Download complete
ea6bc93c489e: Download complete
aeb03d92906a: Download complete
7329a7e9b657: Download complete
Status: Downloaded newer image for mesosphere/kubernetes-mesos:build
Running with args

GOPKG=github.com/mesosphere/kubernetes-mesos
+ GOPKG=github.com/mesosphere/kubernetes-mesos

test ${#} -eq 0 && CMD=( make bootstrap install ) || CMD=( "${@}" )
+ test 0 -eq 0
+ CMD=(make bootstrap install)
test -n "$GOPATH" || GOPATH=/pkg
+ test -n /pkg

# gopath is first directory in GOPATH : separated list
gopath="${GOPATH%%:*}"
+ gopath=/pkg
pkg="${gopath}/src/${GOPKG}"
+ pkg=/pkg/src/github.com/mesosphere/kubernetes-mesos

if [ -d $SNAP ]; then
  test ! -L "${pkg}" || /bin/rm -vf "${pkg}"  # remove any existing link
  parent=$(dirname "${pkg}")
  mkdir -pv "$parent"
  ln -sv $SNAP "$parent/$(basename $GOPKG)"
  cd "${pkg}"
  if [ "x${GIT_BRANCH}" != "x" ]; then
    if test -d '.git'; then
      git checkout "${GIT_BRANCH}"
    else
      echo "ERROR: cannot checkout a branch from non-git-based snapshot" >&2
      exit 1
    fi
  fi
else
  mkdir -pv "${pkg}"
  cd "${pkg}"
  git clone ${GIT_REPO:-https://${GOPKG}.git} .
  test "x${GIT_BRANCH}" = "x" || git checkout "${GIT_BRANCH}"
fi
+ '[' -d /snapshot ']'
+ mkdir -pv /pkg/src/github.com/mesosphere/kubernetes-mesos
mkdir: created directory `/pkg'
mkdir: created directory `/pkg/src'
mkdir: created directory `/pkg/src/github.com'
mkdir: created directory `/pkg/src/github.com/mesosphere'
mkdir: created directory `/pkg/src/github.com/mesosphere/kubernetes-mesos'
+ cd /pkg/src/github.com/mesosphere/kubernetes-mesos
+ git clone https://github.com/mesosphere/kubernetes-mesos.git .
Cloning into '.'...
+ test x = x

exec "${CMD[@]}"
+ exec make bootstrap install
godep restore
package github.com/google/cadvisor/info
    imports github.com/google/cadvisor/info
    imports github.com/google/cadvisor/info: no buildable Go source files in /pkg/src/github.com/google/cadvisor/info
godep: restore: exit status 1
make: *** [bootstrap] Error 1
```

I've tried a few different things and nothing works. Tried checking out version of the dependencies in the GOPATH that this is supposed to use, but that just triggers an old version, using an old dependency, and the whole thing breaks down.

**Comment by jdef** [comment] 2015-03-05 23:31
Thanks for reporting this. @vladimirvivien had the same experience trying to build the release-0.3 branch. It looks like you're building from master. I'll review the Godeps - there might be an easy fix for this.

**Comment by jdef** [comment] 2015-03-05 23:50
data point: starting with a cleanroom environment this also fails:
```shell
$ go get -d github.com/google/cadvisor/api
package github.com/google/cadvisor/api
        imports code.google.com/p/go.exp/inotify
        imports github.com/docker/docker/pkg/mount
        imports github.com/docker/docker/pkg/units
        imports github.com/docker/libcontainer
        imports github.com/Sirupsen/logrus
        imports github.com/docker/libcontainer/cgroups
        imports github.com/docker/libcontainer/cgroups/fs
        imports github.com/docker/libcontainer/cgroups/systemd
        imports github.com/coreos/go-systemd/dbus
        imports github.com/godbus/dbus
        imports github.com/syndtr/gocapability/capability
        imports github.com/docker/libcontainer/network
        imports github.com/docker/libcontainer/network
        imports github.com/docker/libcontainer/network: cannot find package "github.com/docker/libcontainer/network" in any of:
        /usr/local/go/src/github.com/docker/libcontainer/network (from $GOROOT)
        /pkg/src/github.com/docker/libcontainer/network (from $GOPATH)
```

I suspect that, in order to avoid this problem in the future, that we'll need to actually use the \_workspace directory of Godeps as intended intead of hacking around it by using `godep restore`

**Comment by aminjam** [comment] 2015-03-06 00:05
I just ran into the same issue. I think having the _workspace checked in would resolve this issue. I am actually surprised `kubernetes` is still using the `v0.6.2` of `cadvisor`.

**Comment by jdef** [comment] 2015-03-06 06:42
Agreed. I started working on it earlier today. I have something that appears to build. It's kind of ugly. WIP. You can test it out here:

```shell
$ sudo docker run --rm -ti -e GIT_BRANCH=bug_164  mesosphere/kubernetes-mesos:build
```

**Comment by jdef** [comment] 2015-03-06 18:57
There is an ongoing discussion regarding best practices for dependency management: https://groups.google.com/forum/m/?utm_source=golangweekly&utm_medium=email#!msg/golang-dev/nMWoEAG55v8/iJGgur7W_SEJ

**Comment by aminjam** [comment] 2015-03-06 19:07
It's almost as if the creators of the language thought of everything else except package management.

**Closed** 2015-03-10 13:07 UTC
Labels: bug, priority
