### ISSUE TITLE
Pod termination is broken on master due to graceful pod shutdown merge

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#490] opened 2015-09-09 11:50 UTC
It looks like pod termination is broken right now on master for us.

At least the following two e2e tests timeout because pods keep running and endpoints keep existing:

- Kubernetes e2e suite.Services should serve a basic endpoint from pods 	
- Kubernetes e2e suite.Services should serve multiport endpoints from pods

**Comment by sttts** [comment] 2015-09-09 12:07
It was still working at a12b7edc42c5c06a2e7d9f381975658692951d5a, Aug 25

**Comment by sttts** [comment] 2015-09-09 12:35
It was broken 216865b80ac10fa9bba6dc7143ecdb1d2c701757, Sep 3, after our master fix

**Comment by sttts** [comment] 2015-09-09 12:57
a12b7edc42c5c06a2e7d9f381975658692951d5a + out master-fix works as well

**Comment by jdef** [comment] 2015-09-09 13:02
there's been some recent work in the kubelet re: graceful termination of pods. i wonder if this is related?

**Comment by sttts** [comment] 2015-09-09 13:08
yes, can be related.

**Comment by sttts** [comment] 2015-09-09 13:11
`git bisect` is running. let's wait for the result.

**Comment by sttts** [comment] 2015-09-09 15:02
Broken by:
```
commit a7e47cada2b60cbb0122b3d20e3f6b9998789fe1
Merge: 6471796 e5600f7
Author: Derek Carr <decarr@redhat.com>
Date:   Tue Sep 1 15:07:29 2015 -0400

    Merge pull request #12963 from smarterclayton/enable_graceful

    Enable graceful deletion of pods (7/7)
```

**Comment by karlkfi** [comment] 2015-09-09 15:37
Likely a duplicate of #486.

**Comment by sttts** [comment] 2015-09-09 15:41
Yeah, #486 is a symptom of this.

**Comment by sttts** [comment] 2015-09-09 15:42
Same for the broken "endpoint e2e tests".

**Comment by sttts** [comment] 2015-09-14 08:26
Fixed in https://github.com/kubernetes/kubernetes/pull/13909

**Closed** 2015-09-14 15:45 UTC
Labels: area/executor, area/scheduler, bug

**Comment by sttts** [comment] 2015-09-14 17:54
Endpoints work fine with this patch, patch pods still stay in `Terminating` state forever.

Follow-up #495
