### ISSUE TITLE
it is possible to upgrade to a newer version w/o (data/deployment) loss

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#588] opened 2015-10-23 19:04 UTC
Suzie (service op) upgrades from an older version of kubernetes-mesos to a newer version and expects that her cluster will continue to operate normally.
- pods and services are uninterrupted by mesos/k8s upgrades (see #572)
- cluster survives reconfiguration (e.g. executor flags/uri change problem)

**Comment by jdef** [comment] 2015-11-02 20:11
It's been suggested that one approach might be to use a specialized "upgrade" scheduler:
- old scheduler fails over
- upgrade scheduler takes care of pre-upgrade steps, does the upgrade
- post-upgrade: exec into the upgraded, normal scheduler
- mid-upgrade: upon failure, restore old data from backup and re-launch the old scheduler
- executor binaries would need to be relaunched
  - implies pod drain prior during upgrade

**Comment by sttts** [comment] 2016-01-05 15:29
A solution for upgrades is implemented in https://github.com/mesosphere/kubernetes-mesos/issues/324. 

@jdef: I would close this one as a duplicate.

**Comment by sttts** [comment] 2016-01-05 20:31
Duplicate of mesosphere/kubernetes-mesos#324

**Closed by sttts** 2016-01-05 20:31 UTC
Labels: class/duplicate, pqm/maintainability
