### ISSUE TITLE
Investigate conformance without container IP

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#651] opened 2015-11-26 11:30 UTC
As k8sm develop I would like to know where we stand concerning conformance without container IPs,

We target conformance without container IPs for v1.0.0 in https://github.com/mesosphere/kubernetes-mesos/issues/574. Let's start investigations early to know where we are.

TODO:
- [x] add CONTAINER_IPS=false option to dind image
- [x] do a test conformance run in Teamcity with a docker-compose.yml which disables container IPs
- [ ] ~~document the broken tests in issues.md~~
- [x] create another issue to fix the broken tests (if possible), targeted at v0.8.0+

**Comment by sttts** [comment] 2015-12-07 12:36
Adding this to v0.7.1. We should at least be able to document what breaks without container ips. /cc @jdef

I expect this to be only a 3 liner change in the dind image plus a manual run, i.e. not more than an hour of work.

**Comment by sttts** [comment] 2015-12-07 12:38
@karlkfi could you take care of this?

**Comment by karlkfi** [comment] 2015-12-07 16:37
I'll look into it once the license work is wrapped up.

**Comment by sttts** [comment] 2015-12-07 16:48
:+1:

**Comment by karlkfi** [comment] 2015-12-09 02:01
I stared at the wrapdocker networking stuff for a while, trying to grok it, but I'm still not sure what "3 line change" you were implying... Were you thinking that we would just disable the whole `--bip` and `--fixed-cidr` overrides and just use the default bridge?

**Comment by karlkfi** [comment] 2015-12-09 02:44
- added an option to disable the `--bip` and `--fixed-cidr` overrides (disabled by default, enabled by `DOCKER_NETWORK_BRIDGE=true`) 
- docker pushed the test image as `mesosphere/mesos-slave-dind:0.2.4_mesos-0.24.0_docker-1.8.2_ubuntu-14.04.3`.

(I'll make a proper release and re-push once I've verified this works.)

- [X] Successful `./cluster/kube-up.sh`
- [ ] Successful `./cluster/test-smoke.sh`
- [ ] Successful `./cluster/test-conformance.sh`

**Comment by karlkfi** [comment] 2015-12-09 02:48
xref: https://github.com/mesosphere/mesos-slave-dind/pull/7

**Comment by karlkfi** [comment] 2015-12-09 02:55
The guestbook does not pass. Looks like all but one of the redis-slaves failed to come up.

To verify, all you need to do is change the mesos-slave-dind image version in your local docker-compose.yml.

I'll triage more tomorrow.

**Comment by sttts** [comment] 2015-12-09 12:06
We use the guestbook with DCOS to smoke test. This is supposed to work without container IPs.

**Comment by karlkfi** [comment] 2015-12-10 21:44
I've confirmed guestbook-go works when tested manually.

**Comment by karlkfi** [comment] 2015-12-10 21:46
Regular guestbook fails to come up. lots of InsufficientFreeMemory and ContainerCreating statuses.

**Comment by karlkfi** [comment] 2015-12-10 22:08
Confirmed that the InsufficientFreeMemory errors happen locally on my machine with the current (older) version of mesos-slave-dind, and that the smoke test is passing on master on CI. So my local docker-machine might be having issues.

**Comment by karlkfi** [comment] 2015-12-10 23:09
Looks like the nodes think they're full. They report capacity of `memory: 448Mi` even tho each mesos-slave is configured with `mem:1280`. And the guestbook containers all have like 100Mi reserved each.

```
./cluster/kubectl.sh describe node 172.17.0.6
...
Capacity:
 cpu:		0
 memory:	448Mi
 pods:		40
...
Non-terminated Pods:		(5 in total)
  Namespace			Name				CPU Requests			CPU Limits			Memory Requests	Memory Limits
  ---------			----				------------			----------			---------------	-------------
  default			frontend-dv711			100m (-9223372036854775808%)	0 (-9223372036854775808%)	100Mi (22%)	0 (0%)
  default			redis-slave-br5bk		100m (-9223372036854775808%)	0 (-9223372036854775808%)	100Mi (22%)	0 (0%)
  default			redis-slave-ngfj7		100m (-9223372036854775808%)	0 (-9223372036854775808%)	100Mi (22%)	0 (0%)
  kube-system			kube-ui-v3-qe9l9		100m (-9223372036854775808%)	100m (-9223372036854775808%)	50Mi (11%)	50Mi (11%)
  static-pods			busybox-172.17.0.6		250m (-9223372036854775808%)	250m (-9223372036854775808%)	64Mi (14%)	64Mi (14%)
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests			CPU Limits			Memory Requests	Memory Limits
  ------------			----------			---------------	-------------
  650m (-9223372036854775808%)	350m (-9223372036854775808%)	414Mi (92%)	114Mi (25%)
```

```
$ ./cluster/kubectl.sh describe node 172.17.0.9
...
Capacity:
 cpu:		0
 memory:	448Mi
 pods:		40
...
Non-terminated Pods:		(4 in total)
  Namespace			Name				CPU Requests			CPU Limits			Memory Requests	Memory Limits
  ---------			----				------------			----------			---------------	-------------
  default			frontend-7yws4			100m (-9223372036854775808%)	0 (-9223372036854775808%)	100Mi (22%)	0 (0%)
  default			frontend-rlaqq			100m (-9223372036854775808%)	0 (-9223372036854775808%)	100Mi (22%)	0 (0%)
  kube-system			kube-dns-v9-i5fm7		310m (-9223372036854775808%)	310m (-9223372036854775808%)	170Mi (37%)	170Mi (37%)
  static-pods			busybox-172.17.0.9		250m (-9223372036854775808%)	250m (-9223372036854775808%)	64Mi (14%)	64Mi (14%)
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests			CPU Limits			Memory Requests	Memory Limits
  ------------			----------			---------------	-------------
  760m (-9223372036854775808%)	560m (-9223372036854775808%)	434Mi (96%)	234Mi (52%)
```

**Comment by karlkfi** [comment] 2015-12-11 01:12
@jdef Found the problem: 
The memory is not aggregating the memory allocated to all roles, just the last one: https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/executor/executor.go#L1025

This is fixed by https://github.com/kubernetes/kubernetes/pull/18348 which is waiting for merge (submit queue is blocked).

**Comment by karlkfi** [comment] 2015-12-11 01:21
Confirmed smoke test succeeds locally on the `mesosphere/sur-652-conformance-tests` branch.

**Comment by karlkfi** [comment] 2015-12-11 02:19
I ran conformance against the `mesosphere/sur-652-conformance-tests` branch for a baseline.
I'll run it with container IPs disabled tomorrow (hopefully the PR is merged by then), but I expect that to take longer with more failures timing out.

```
$ KUBECONFIG=~/.kube/config ./cluster/test-conformance.sh 2>&1 | tee conformance.log
...
Summarizing 3 Failures:

[Fail] Events [It] should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/events.go:127

[Fail] Downward API volume [It] should update annotations on modification [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/downwardapi_volume.go:142

[Fail] Downward API volume [It] should update labels on modification [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/downwardapi_volume.go:106

Ran 79 of 206 Specs in 3189.841 seconds
FAIL! -- 76 Passed | 3 Failed | 1 Pending | 126 Skipped --- FAIL: TestE2E (3189.90s)
FAIL

Ginkgo ran 1 suite in 53m10.430897591s
```

**Comment by karlkfi** [comment] 2015-12-11 02:26
I've confirmed that the smoke tests pass on the `mesosphere/sur-652-conformance-tests` branch with container IPs disabled.

**Comment by karlkfi** [comment] 2015-12-11 18:25
Conformance on the `mesosphere/sur-652-conformance-tests` branch (a lot less failures than I expected!):

```
$ KUBECONFIG=~/.kube/config ./cluster/test-conformance.sh 2>&1 | tee conformance.log
...
Summarizing 10 Failures:

[Fail] Downward API volume [It] should update labels on modification [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/downwardapi_volume.go:106

[Fail] Kubectl client Update Demo [It] should create and stop a replication controller [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1098

[Fail] Kubectl client Update Demo [It] should do a rolling update of a replication controller [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1098

[Fail] Downward API volume [It] should update annotations on modification [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/downwardapi_volume.go:142

[Fail] PreStop [It] should call prestop when killing a pod [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/pre_stop.go:142

[Fail] Kubectl client Update Demo [It] should scale a replication controller [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1098

[Fail] Proxy version v1 [It] should proxy through a service and a pod [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/proxy.go:221

[Fail] ReplicationController [It] should serve a basic image on each replica with a public image [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/rc.go:117

[Fail] Events [It] should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/events.go:127

[Fail] [Example] ClusterDns [It] should create pod that uses dns [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/example_cluster_dns.go:111

Ran 79 of 206 Specs in 4512.246 seconds
FAIL! -- 69 Passed | 10 Failed | 1 Pending | 126 Skipped --- FAIL: TestE2E (4512.35s)
FAIL

Ginkgo ran 1 suite in 1h15m13.348804419s
Test Suite Failed
```

**Comment by karlkfi** [comment] 2015-12-11 19:38
TODO: 
- [ ] cut release/tag of mesos-slave-dind
- [ ] make container ips optional from mesos/docker kube-up (to enable testing on CI)

**Comment by karlkfi** [comment] 2015-12-11 21:22
Kubernetes-Mesos Conformance (without container IP network overlay) full log:
https://gist.github.com/karlkfi/d6a2259dd1c87ec2b8e6

Investigation complete. Follow up in #699

**Comment by sttts** [comment] 2015-12-16 16:26
As far as I can see only half of the ticket is done.

**Comment by karlkfi** [comment] 2015-12-17 20:12
I tried running another conformance suite and the following test hung indefinitely:

```
Kubectl client Kubectl run --rm job
  should create a job from an image, then delete the job [Conformance]
  /Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:881
[BeforeEach] Kubectl client
  /Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework.go:62
STEP: Creating a kubernetes client
Dec 17 11:02:47.075: INFO: >>> testContext.KubeConfig: /Users/karl/.kube/config

STEP: Building a namespace api object
Dec 17 11:02:47.080: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-kubectl-03h51
Dec 17 11:02:47.095: INFO: Service account default in ns e2e-tests-kubectl-03h51 had 0 secrets, ignoring for 2s: <nil>
Dec 17 11:02:49.100: INFO: Service account default in ns e2e-tests-kubectl-03h51 with secrets found. (2.020046774s)
STEP: Waiting for a default service account to be provisioned in namespace
Dec 17 11:02:49.100: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-kubectl-03h51
Dec 17 11:02:49.102: INFO: Service account default in ns e2e-tests-kubectl-03h51 with secrets found. (1.502867ms)
[BeforeEach] Kubectl client
  /Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:85
[It] should create a job from an image, then delete the job [Conformance]
  /Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:881
STEP: executing a command with run --rm and attach with stdin
Dec 17 11:02:49.103: INFO: Running '/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/bin/darwin/amd64/kubectl --server=https://172.17.0.5:6443 --kubeconfig=/Users/karl/.kube/config --namespace= run e2e-test-rm-busybox-job --image=busybox --rm=true --restart=Never --attach=true --stdin -- sh -c cat && echo 'stdin closed''
```

**Comment by karlkfi** [comment] 2015-12-17 23:12
Master is now failing 5 more tests AND all the new job tests I had to exclude, because they hang.

```
KUBECONFIG=~/.kube/config ./cluster/test-conformance.sh -ginkgo.skip='should.create.a.job' -ginkgo.randomizeAllSpecs=false 2>&1 | tee conformance.log
....
Summarizing 15 Failures:

[Fail] Pods [It] should have monotonically increasing restart count [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/pods.go:86

[Fail] Kubectl client Update Demo [It] should create and stop a replication controller [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1108

[Fail] Kubectl client Update Demo [It] should scale a replication controller [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1108

[Fail] Kubectl client Update Demo [It] should do a rolling update of a replication controller [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1108

[Fail] ReplicationController [It] should serve a basic image on each replica with a public image [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/rc.go:117

[Fail] EmptyDir volumes when FSGroup is specified [Skipped] [It] new files should be created with FSGroup ownership when container is root [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1251

[Fail] EmptyDir volumes when FSGroup is specified [Skipped] [It] new files should be created with FSGroup ownership when container is non-root [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1251

[Fail] EmptyDir volumes when FSGroup is specified [Skipped] [It] volume on default medium should have the correct mode using FSGroup [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1251

[Fail] EmptyDir volumes when FSGroup is specified [Skipped] [It] volume on tmpfs should have the correct mode using FSGroup [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1251

[Fail] Proxy version v1 [It] should proxy through a service and a pod [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/proxy.go:220

[Fail] [Example] ClusterDns [It] should create pod that uses dns [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/example_cluster_dns.go:110

[Fail] Downward API volume [It] should provide podname as non-root with fsgroup [Conformance] [Skipped]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:1251

[Fail] Downward API volume [It] should update labels on modification [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/downwardapi_volume.go:106

[Fail] Downward API volume [It] should update annotations on modification [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/downwardapi_volume.go:142

[Fail] PreStop [It] should call prestop when killing a pod [Conformance]
/Users/karl/workspace/k8s-master/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/pre_stop.go:142

Ran 82 of 207 Specs in 4928.236 seconds
FAIL! -- 67 Passed | 15 Failed | 1 Pending | 124 Skipped --- FAIL: TestE2E (4928.30s)
FAIL

Ginkgo ran 1 suite in 1h22m8.63905889s
Test Suite Failed
```

**Comment by karlkfi** [comment] 2015-12-18 01:35
TODO: Create tickets for the errors:

- [ ] Pods [It] should have monotonically increasing restart count (Flakey?)
- [ ] Kubectl client Update Demo [It] should create and stop a replication controller
- [ ] Kubectl client Update Demo [It] should do a rolling update of a replication controller
- [ ] Kubectl client Update Demo [It] should scale a replication controller
- [ ] Events [It] should be sent by kubelets and the scheduler about pods scheduling and running (Flakey?) 
- [ ] ReplicationController [It] should serve a basic image on each replica with a public image
- [ ] Proxy version v1 [It] should proxy through a service and a pod
- [ ] [Example] ClusterDns [It] should create pod that uses dns
- [X] Downward API volume [It] should update labels on modification - #17917
- [X] Downward API volume [It] should update annotations on modification - #17917
- [ ] PreStop [It] should call prestop when killing a pod

**Comment by karlkfi** [comment] 2015-12-18 02:13
I didn't create tickets for the flakey tests. I figure we can handle those once DCOS testing is in CI.

**Comment by karlkfi** [comment] 2015-12-18 02:14
I don't think we need to document these things in known issues, at least until they've been triaged and the root cause is known. Some of them could just be bad test methodology, not missing functionality. We should probably document any of them that aren't working before the v0.8.0 release tho.

**Comment by karlkfi** [comment] 2015-12-18 02:15
re-openning for review. @sttts please close if it looks ok.

**Comment by sttts** [comment] 2015-12-18 10:13
Very good. Thanks @karlkfi. I agree about issues.md for the moment.

**Closed** 2015-12-18 10:16 UTC
Labels: PTAL, tests/conformance, tests/e2e
