### ISSUE TITLE
Activate dcos subcommand in multiverse

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#589] opened 2015-10-23 19:10 UTC
Use alice wants to use kubectl via the dcos tool, without the need to download the correct kubectl binary manually from a Github release of the dcos package.

**Comment by treilly1969** [comment] 2015-10-25 02:29
Hi,

I'm uncertain where the state of calling kubectl via dcos command line is at from seeing this issue.

I viewed a recording/demo on YouTube the other day, posted a while ago, that implied that running kubectl was implicitly available  is dcosby just adding the kubernetes package. Separately, there are some old readme instructions on GitHub that refer to using curl commands to get ikubectl working against a kubernetes cluster started on mesosphere. My testing in last few days indicates it is not implicitly available in dcos by adding the kubernetes package. I'd prefer not to try and work the old readme curl instructions as I would hope it would be simpler.

Was the YouTube clip from a while ago false advertising or am I missing some steps that are still being worked through to get kubectl implicitly available without additional steps after the kubernetes package has been deployed to mesosphere?

Sorry for my ignorance if any of this isn't making sense.

Thanks

Tommy

**Comment by jdef** [comment] 2015-10-25 03:45
Thanks for sending in this question. Not sure what youtube clip you're
referring to. There's currently work in progress to enable `dcos kubectl
...` as a subcommand for the DCOS CLI. Until then you can curl against the
REST API or download the kubectl releases as per the docs:
https://docs.mesosphere.com/services/kubernetes/

**Comment by treilly1969** [comment] 2015-10-25 17:17
That's great, this will simplify the use of kubernetes on mesosphere further. Looking forward to seeing it.

The YouTube clip I was alluding to is at http://youtu.be/0I6qG9RQUnY - about 5 minutes in it shows the kubernetes package being installed from the dcos command line and then immediately followed by a "dcos kubectl create -f kubernetes-job.json".

**Comment by jdef** [comment] 2015-11-01 20:04
xref #564

**Comment by jdef** [comment] 2015-11-01 20:06
xref https://github.com/mesosphere/multiverse/pull/28

**Comment by jdef** [comment] 2015-11-03 17:38
duplicate of #408

**Closed** 2015-11-03 17:38 UTC
Labels: duplicate, integration/DCOS
